### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by Zak223** [JourneyintoDarkness/JourneyintoDarknessPack#5]
- [x] Add [GroovyScript](https://www.curseforge.com/minecraft/mc-mods/groovyscript)
- [x] Add [Resource Loader](https://www.curseforge.com/minecraft/mc-mods/resource-loader)
- [x] Add [Custom Main Menu](https://www.curseforge.com/minecraft/mc-mods/custom-main-menu)
- [x] Add [Multiblocked](https://www.curseforge.com/minecraft/mc-mods/multiblocked)
- [x] Add [Had Enough Items](https://www.curseforge.com/minecraft/mc-mods/had-enough-items)
- [x] Send Purplik new zip
